spring.application.name=banking-service

# Enables the H2 console so you can see the database in your browser
spring.h2.console.enabled=true
# Sets the database name
spring.datasource.url=jdbc:h2:mem:testdb
# Required for Spring Boot 4.x
spring.jpa.hibernate.ddl-auto=update